#First input file is the blast results with output format of 6, which you can find an example of it in BltFastaSub object.
#qseqid	qlen	sseqid	slen	qstart	qend	sstart	send	evalue	bitscore	score	length	pident	nident	mismatch	positive	gapopen	gaps	ppos	qframe	qcovhsp	qseq	qseq_full
#NS500198:409:HKTHLAFXY:1:11101:19405:13594	60	ND4_loc_10760_12137	52	1	52	1	52	6.26e-25	97.1	52	52	100.000	52	0	52	00	100.00	1	87	CCCATTCTCCTCCTATCCCTCAACCCCGACATCATTACCGGGTTTTCCTCTT	cccattctcctcctatccctcaaccccgacatcattaccgggttttcctcttAAAAAAAA

# second input files required is the primer coordinate file, which you can find it in StopCodon object
#ID	Stop_Seq	prim5_coordinate	Length_of_the_primer	GSP_seq	Extra_seq
#ND6_loc_complement14149_14673	ATAGG	63	26	GTTACTGGTTGAACATTGTTTGTTGG	CCCCTACTCCTCCTAGACCTAACCTGACTAGAAAAGCTATTACCTAAAACAATTTCACAGCACCAAATCTCCACCTCCATCATCACCTCAACCCAAAAAGGCATAATTAAACTTTACTTCCTCTCTTTCTTCTTCCCACTCATCCTAACCCTACTCCTAATCACATAA

#Load supplementaryData.RData to find an example and supplementary data.
load("supplementaryData.RData")

#Read in your blast table which has been generated by your command line in unix OS, and filter.
# BltFastaSub=list()
# for (i in 1:length(BltFasta)){
#   BltFastaSub[[i]]=BltFasta[[i]][as.vector(BltFasta[[i]]$sseqid) %in% as.vector(StopCodon$ID),]
# }
# names(BltFastaSub)=names(BltFasta)

#find polyA+ tail and define them by length with referring to reference genome (ref. genome ID#: J01415), and add $ReadGroup column to original blast table
for (i in 1:length(BltFastaSub)){
  #Get the sequences from blast table, and break them to uppercase  (unaligned sequence) and lowercase (aligned sequence) sections
  T=sapply(BltFastaSub[[i]][,23], function(x) str_extract_all(as.vector(x),"A-Z][a-z]*|[a-z]+|[A-Z]+"))
  #Make matrix to append the sequence mining
  MatT=matrix(NA,length(T),1)
  for (j in 1:length(T)){
    #Collect the stop codon from the reference genome
    Scod=tolower(as.character(StopCodon[grep(as.vector(BltFastaSub[[i]]$sseqid[j]),StopCodon$ID),]$Stop_Seq))
    #Get the coordinate of designed primer for each mitochondrial coding sequences
    Len=StopCodon[grep(as.vector(BltFastaSub[[i]]$sseqid[j]),StopCodon$ID),][,3]
    #if statement to classify 3' ends of the sequences
    if (length(T[[j]]) == 1 && grepl("^[a-z]+$", T[[j]][1], perl=T)){
      #get 5 last nucleotides from the sequence
      Qcod=paste(strsplit(T[[j]],"")[[1]][(length(strsplit(T[[j]],"")[[1]])-4):length(strsplit(T[[j]],"")[[1]])],collapse="")
      #Assign a flag to each sequence based on 3' end of sequences
      if (Qcod == Scod && nchar(T[[j]]) == Len){MatT[j,1]="TrueEnd"}
      else if (Qcod != Scod && nchar(T[[j]]) == Len){MatT[j,1]="notrueend"}
      else if (Qcod == Scod && nchar(T[[j]]) > Len){MatT[j,1]="Long_TrueEnd"}
      else if (Qcod != Scod && nchar(T[[j]]) > Len){MatT[j,1]="Long_notrueend"}
      else if (Qcod == Scod && nchar(T[[j]]) < Len){MatT[j,1]="Short_TrueEnd"}
      else if (Qcod != Scod && nchar(T[[j]]) < Len){MatT[j,1]="Short_notrueend"}
    }
    if (length(T[[j]]) == 2 && grepl("^[a-z]+$", T[[j]][2], perl=T)){
      #get 5 last nucleotides from the sequence
      Qcod=paste(strsplit(T[[j]][[2]],"")[[1]][(length(strsplit(T[[j]][[2]],"")[[1]])-4):length(strsplit(T[[j]][[2]],"")[[1]])],collapse="")
      #Assign a flag to each sequence based on 3' end of sequences
      if (Qcod == Scod && nchar(T[[j]][[2]]) == Len){MatT[j,1]="TrueEnd"}
      else if (Qcod != Scod && nchar(T[[j]][[2]]) == Len){MatT[j,1]="notrueend"}
      else if (Qcod == Scod && nchar(T[[j]][[2]]) > Len){MatT[j,1]="Long_TrueEnd"}
      else if (Qcod != Scod && nchar(T[[j]][[2]]) > Len){MatT[j,1]="Long_notrueend"}
      else if (Qcod == Scod && nchar(T[[j]][[2]]) < Len){MatT[j,1]="Short_TrueEnd"}
      else if (Qcod != Scod && nchar(T[[j]][[2]]) < Len){MatT[j,1]="Short_notrueend"}
    }
    #if statement to classify 3' ends of the sequences with flanking sequence only at 3'
    if (length(T[[j]]) == 2 && grepl("^[a-z]+$", T[[j]][1], perl=T)){
      #Get the flanking sequence.
      Target=as.character(T[[j]][[2]])
      #get 5 last nucleotides from the sequence.
      Qcod=paste(strsplit(T[[j]][[1]],"")[[1]][(length(strsplit(T[[j]][[1]],"")[[1]])-4):length(strsplit(T[[j]][[1]],"")[[1]])],collapse="")
      #extract the equal number of Target nucleotides from the reference genome sequence after the stop codon of each coding sequences.
      xSeq=as.character(paste(strsplit(StopCodon[match(as.vector(BltFastaSub[[i]]$sseqid)[j],StopCodon$ID),]$Extra_seq,"")[[1]][1:nchar(Target)],collapse=""))
      #Assign a flag to each sequence based on 3' end of sequences
      if (Qcod == Scod && nchar(T[[j]][[1]]) == Len){
        if(grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) <= 1 && Target != "A"){MatT[j,1]="TrueEnd"}
        else if (!grepl("^[AA]+$", Target, perl=T) && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) != "NaN" && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) == 100){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="TrueEnd_Extra"}
        }
        else if (str_detect(Target, "^A+$")  && nchar(Target) >= 1){MatT[j,1]="TrueEnd_OligoA"}
        else if (grepl("^[A-Z]+", Target, perl=T) && (str_detect(Target, "^AAA+") || str_detect(Target, "AAA+$")) && length(table(unlist(strsplit(Target,"")))) >= 2){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) > 2 && ((str_detect(Target, "^AAAA+") && str_detect(Target, "AAA+$")) || (str_detect(Target, "^AAAA+") || str_detect(Target, "AAA+$")))  && length(names(table(strsplit(Target,"")[[1]]))) > 2){MatT[j,1]="TrueEnd_ExtraOligoA"}
          else if (grepl("^[A-Z]+", Target, perl=T) && nchar(Target) >=4 && str_detect(paste(strsplit(Target,"")[[1]][1:(length(strsplit(Target,"")[[1]])-3)],collapse=""),"AAAAAA+$")){MatT[j,1]="TrueEnd_OligoA"}
          else if (str_detect(Target, "AA+$") && nchar(Target) >= 2){MatT[j,1]="TrueEnd_OligoA"}
          else if ((grepl("^[AA]+", Target, perl=T) || grepl("[AA]+$", Target, perl=T)) && length(table(unlist(strsplit(Target,"")))) <= 2 && nchar(Target) >= 2){MatT[j,1]="TrueEnd_OligoA"}
          else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && ((!str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) || !str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="TrueEnd_Extra"}
        }
        else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="TrueEnd_Extra"}
      }
      if (Qcod != Scod && nchar(T[[j]][[1]]) == Len){
        if(grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) <= 1 && Target != "A"){MatT[j,1]="notrueend"}
        else if (!grepl("^[AA]+$", Target, perl=T) && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) != "NaN" && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) == 100){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="notrueend_Extra"}
        }
        else if (str_detect(Target, "^A+$") && nchar(Target) >= 1){MatT[j,1]="notrueend_OligoA"}
        else if (grepl("^[A-Z]+", Target, perl=T) && (str_detect(Target, "^AAA+") || str_detect(Target, "AAA+$")) && length(table(unlist(strsplit(Target,"")))) >= 2){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) > 2 && ((str_detect(Target, "^AAAA+") && str_detect(Target, "AAA+$")) || (str_detect(Target, "^AAAA+") || str_detect(Target, "AAA+$")))  && length(names(table(strsplit(Target,"")[[1]]))) > 2){MatT[j,1]="notrueend_ExtraOligoA"}
          else if (grepl("^[A-Z]+", Target, perl=T) && nchar(Target) >=4 && str_detect(paste(strsplit(Target,"")[[1]][1:(length(strsplit(Target,"")[[1]])-3)],collapse=""),"AAAAAA+$")){MatT[j,1]="notrueend_OligoA"}
          else if (str_detect(Target, "AA+$") && nchar(Target) >= 2){MatT[j,1]="notrueend_OligoA"}
          else if ((grepl("^[AA]+", Target, perl=T) || grepl("[AA]+$", Target, perl=T)) && length(table(unlist(strsplit(Target,"")))) <= 2 && nchar(Target) >= 2){MatT[j,1]="notrueend_OligoA"}
          else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && ((!str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) || !str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="notrueend_Extra"}
        }
        else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="notrueend_Extra"}
      }
      if (Qcod == Scod && nchar(T[[j]][[1]]) > Len){
        if(grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) <= 1 && Target != "A"){MatT[j,1]="Long_TrueEnd"}
        else if (!grepl("^[AA]+$", Target, perl=T) && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) != "NaN" && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) == 100){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Long_TrueEnd_Extra"}
        }
        else if (str_detect(Target, "^A+$") && nchar(Target) >= 1){MatT[j,1]="Long_TrueEnd_OligoA"}
        else if (grepl("^[A-Z]+", Target, perl=T) && (str_detect(Target, "^AAA+") || str_detect(Target, "AAA+$")) && length(table(unlist(strsplit(Target,"")))) >= 2){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) > 2 && ((str_detect(Target, "^AAAA+") && str_detect(Target, "AAA+$")) || (str_detect(Target, "^AAAA+") || str_detect(Target, "AAA+$")))  && length(names(table(strsplit(Target,"")[[1]]))) > 2){MatT[j,1]="Long_TrueEnd_ExtraOligoA"}
          else if (grepl("^[A-Z]+", Target, perl=T) && nchar(Target) >=4 && str_detect(paste(strsplit(Target,"")[[1]][1:(length(strsplit(Target,"")[[1]])-3)],collapse=""),"AAAAAA+$")){MatT[j,1]="Long_TrueEnd_OligoA"}
          else if (str_detect(Target, "AA+$") && nchar(Target) >= 2){MatT[j,1]="Long_TrueEnd_OligoA"}
          else if ((grepl("^[AA]+", Target, perl=T) || grepl("[AA]+$", Target, perl=T)) && length(table(unlist(strsplit(Target,"")))) <= 2 && nchar(Target) >= 2){MatT[j,1]="Long_TrueEnd_OligoA"}
          else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && ((!str_detect(Target, "^AAAA+") && !str_detect(Target, "AAA+$")) || !str_detect(Target, "^AAAA+") && !str_detect(Target, "AAA+$")) && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Long_TrueEnd_Extra"}
        }
        else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Long_TrueEnd_Extra"}
      }
      if (Qcod != Scod && nchar(T[[j]][[1]]) > Len){
        if(grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) <= 1 && Target != "A"){MatT[j,1]="Long_notrueend"}
        else if (!grepl("^[AA]+$", Target, perl=T) && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) != "NaN" && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) == 100){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Long_notrueend_Extra"}
        }
        else if (str_detect(Target, "^A+$") && nchar(Target) >= 1){MatT[j,1]="Long_notrueend_OligoA"}
        else if (grepl("^[A-Z]+", Target, perl=T) && (str_detect(Target, "^AAA+") || str_detect(Target, "AAA+$")) && length(table(unlist(strsplit(Target,"")))) >= 2){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) > 2 && ((str_detect(Target, "^AAAA+") && str_detect(Target, "AAA+$")) || (str_detect(Target, "^AAAA+") || str_detect(Target, "AAA+$")))  && length(names(table(strsplit(Target,"")[[1]]))) > 2){MatT[j,1]="Long_notrueend_ExtraOligoA"}
          else if (grepl("^[A-Z]+", Target, perl=T) && nchar(Target) >=4 && str_detect(paste(strsplit(Target,"")[[1]][1:(length(strsplit(Target,"")[[1]])-3)],collapse=""),"AAAAAA+$")){MatT[j,1]="long_notrueend_OligoA"}
          else if (str_detect(Target, "AA+$") && nchar(Target) >= 2){MatT[j,1]="Long_notrueend_OligoA"}
          else if ((grepl("^[AA]+", Target, perl=T) || grepl("[AA]+$", Target, perl=T)) && length(table(unlist(strsplit(Target,"")))) <= 2 && nchar(Target) >= 2){MatT[j,1]="Long_notrueend_OligoA"}
          else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && ((!str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) || !str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Long_notrueend_Extra"}
        }
        else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Long_notrueend_Extra"}
      }
      if (Qcod == Scod && nchar(T[[j]][[1]]) < Len){
        if(grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) <= 1 && Target != "A"){MatT[j,1]="Short_TrueEnd"}
        else if (!grepl("^[AA]+$", Target, perl=T) && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) != "NaN" && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) == 100){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Short_TrueEnd_Extra"}
        }
        else if (str_detect(Target, "^A+$") && nchar(Target) >= 1){MatT[j,1]="Short_TrueEnd_OligoA"}
        else if (grepl("^[A-Z]+", Target, perl=T) && (str_detect(Target, "^AAA+") || str_detect(Target, "AAA+$")) && length(table(unlist(strsplit(Target,"")))) >= 2){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) > 2 && ((str_detect(Target, "^AAAA+") && str_detect(Target, "AAA+$")) || (str_detect(Target, "^AAAA+") || str_detect(Target, "AAA+$")))  && length(names(table(strsplit(Target,"")[[1]]))) > 2){MatT[j,1]="Short_TrueEnd_ExtraOligoA"}
          else if (grepl("^[A-Z]+", Target, perl=T) && nchar(Target) >=4 && str_detect(paste(strsplit(Target,"")[[1]][1:(length(strsplit(Target,"")[[1]])-3)],collapse=""),"AAAAAA+$")){MatT[j,1]="Short_TrueEnd_OligoA"}
          else if (str_detect(Target, "AA+$") && nchar(Target) >= 2){MatT[j,1]="Short_TrueEnd_OligoA"}
          else if ((grepl("^[AA]+", Target, perl=T) || grepl("[AA]+$", Target, perl=T)) && length(table(unlist(strsplit(Target,"")))) <= 2 && nchar(Target) >= 2){MatT[j,1]="Short_TrueEnd_OligoA"}
          else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && ((!str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) || !str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Short_TrueEnd_Extra"}
        }
        else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Short_TrueEnd_Extra"}
      }
      if (Qcod != Scod && nchar(T[[j]][[1]]) < Len){
        if(grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) <= 1 && Target != "A"){MatT[j,1]="Short_notrueend"}
        else if (!grepl("^[AA]+$", Target, perl=T) && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) != "NaN" && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) == 100){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Short_notrueend_Extra"}
        }
        else if (str_detect(Target, "^A+$") && nchar(Target) >= 1){MatT[j,1]="Short_notrueend_OligoA"}
        else if (grepl("^[A-Z]+", Target, perl=T) && (str_detect(Target, "^AAA+") || str_detect(Target, "AAA+$")) && length(table(unlist(strsplit(Target,"")))) >= 2){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) > 2 && ((str_detect(Target, "^AAAA+") && str_detect(Target, "AAA+$")) || (str_detect(Target, "^AAAA+") || str_detect(Target, "AAA+$")))  && length(names(table(strsplit(Target,"")[[1]]))) > 2){MatT[j,1]="Short_notrueend_ExtraOligoA"}
          else if (grepl("^[A-Z]+", Target, perl=T) && nchar(Target) >=4 && str_detect(paste(strsplit(Target,"")[[1]][1:(length(strsplit(Target,"")[[1]])-3)],collapse=""),"AAAAAA+$")){MatT[j,1]="Short_notrueend_OligoA"}
          else if (str_detect(Target, "AA+$") && nchar(Target) >= 2){MatT[j,1]="Short_notrueend_OligoA"}
          else if ((grepl("^[AA]+", Target, perl=T) || grepl("[AA]+$", Target, perl=T)) && length(table(unlist(strsplit(Target,"")))) <= 2 && nchar(Target) >= 2){MatT[j,1]="Short_notrueend_OligoA"}
          else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && ((!str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) || !str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Short_notrueend_Extra"}
        }
        else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Short_notrueend_Extra"}
      }
    }
    #####################################################################
    #if statement to classify 3' ends of the sequences with flanking sequences at 5' and 3'.
    if (length(T[[j]]) == 3 && grepl("^[a-z]+$", T[[j]][2], perl=T)){
      Target=as.character(T[[j]][[3]])
      #get 5 last nucleotides from the sequence
      Qcod=paste(strsplit(T[[j]][[2]],"")[[1]][(length(strsplit(T[[j]][[2]],"")[[1]])-4):length(strsplit(T[[j]][[2]],"")[[1]])],collapse="")
      #extract the equal number of Target nucleotides from the reference genome sequence after the stop codon of each coding sequences.
      xSeq=as.character(paste(strsplit(StopCodon[match(as.vector(BltFastaSub[[i]]$sseqid)[j],StopCodon$ID),]$Extra_seq,"")[[1]][1:nchar(Target)],collapse=""))
      if (Qcod == Scod && nchar(T[[j]][[2]]) == Len){
        if(grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) <= 1 && Target != "A"){MatT[j,1]="TrueEnd"}
        else if (!grepl("^[AA]+$", Target, perl=T) && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) != "NaN" && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) == 100){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="TrueEnd_Extra"}
        }
        else if (str_detect(Target, "^A+$") && nchar(Target) >= 1){MatT[j,1]="TrueEnd_OligoA"}
        else if (grepl("^[A-Z]+", Target, perl=T) && (str_detect(Target, "^AAA+") || str_detect(Target, "AAA+$")) && length(table(unlist(strsplit(Target,"")))) >= 2){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) > 2 && ((str_detect(Target, "^AAAA+") && str_detect(Target, "AAA+$")) || (str_detect(Target, "^AAAA+") || str_detect(Target, "AAA+$")))  && length(names(table(strsplit(Target,"")[[1]]))) > 2){MatT[j,1]="TrueEnd_ExtraOligoA"}
          else if (grepl("^[A-Z]+", Target, perl=T) && nchar(Target) >=4 && str_detect(paste(strsplit(Target,"")[[1]][1:(length(strsplit(Target,"")[[1]])-3)],collapse=""),"AAAAAA+$")){MatT[j,1]="TrueEnd_OligoA"}
          else if (str_detect(Target, "AA+$") && nchar(Target) >= 2){MatT[j,1]="TrueEnd_OligoA"}
          else if ((grepl("^[AA]+", Target, perl=T) || grepl("[AA]+$", Target, perl=T)) && length(table(unlist(strsplit(Target,"")))) <= 2 && nchar(Target) >= 2){MatT[j,1]="TrueEnd_OligoA"}
          else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && ((!str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) || !str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="TrueEnd_Extra"}
        }
        else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="TrueEnd_Extra"}
      }
      if (Qcod != Scod && nchar(T[[j]][[2]]) == Len){
        if(grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) <= 1 && Target != "A"){MatT[j,1]="notrueend"}
        else if (!grepl("^[AA]+$", Target, perl=T) && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) != "NaN" && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) == 100){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="notrueend_Extra"}
        }
        else if (str_detect(Target, "^A+$") && nchar(Target) >= 1){MatT[j,1]="notrueend_OligoA"}
        else if (grepl("^[A-Z]+", Target, perl=T) && (str_detect(Target, "^AAA+") || str_detect(Target, "AAA+$")) && length(table(unlist(strsplit(Target,"")))) >= 2){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) > 2 && ((str_detect(Target, "^AAAA+") && str_detect(Target, "AAA+$")) || (str_detect(Target, "^AAAA+") || str_detect(Target, "AAA+$")))  && length(names(table(strsplit(Target,"")[[1]]))) > 2){MatT[j,1]="notrueend_ExtraOligoA"}
          else if (grepl("^[A-Z]+", Target, perl=T) && nchar(Target) >=4 && str_detect(paste(strsplit(Target,"")[[1]][1:(length(strsplit(Target,"")[[1]])-3)],collapse=""),"AAAAAA+$")){MatT[j,1]="notrueend_OligoA"}
          else if (str_detect(Target, "AA+$") && nchar(Target) >= 2){MatT[j,1]="notrueend_OligoA"}
          else if ((grepl("^[AA]+", Target, perl=T) || grepl("[AA]+$", Target, perl=T)) && length(table(unlist(strsplit(Target,"")))) <= 2 && nchar(Target) >= 2){MatT[j,1]="notrueend_OligoA"}
          else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && ((!str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) || !str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="notrueend_Extra"}
        }
        else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="notrueend_Extra"}
      }
      if (Qcod == Scod && nchar(T[[j]][[2]]) > Len){
        if(grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) <= 1 && Target != "A"){MatT[j,1]="Long_TrueEnd"}
        else if (!grepl("^[AA]+$", Target, perl=T) && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) != "NaN" && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) == 100){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Long_TrueEnd_Extra"}
        }
        else if (str_detect(Target, "^A+$") && nchar(Target) >= 1){MatT[j,1]="Long_TrueEnd_OligoA"}
        else if (grepl("^[A-Z]+", Target, perl=T) && (str_detect(Target, "^AAA+") || str_detect(Target, "AAA+$")) && length(table(unlist(strsplit(Target,"")))) >= 2){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) > 2 && ((str_detect(Target, "^AAAA+") && str_detect(Target, "AAA+$")) || (str_detect(Target, "^AAAA+") || str_detect(Target, "AAA+$")))  && length(names(table(strsplit(Target,"")[[1]]))) > 2){MatT[j,1]="Long_TrueEnd_ExtraOligoA"}
          else if (grepl("^[A-Z]+", Target, perl=T) && nchar(Target) >=4 && str_detect(paste(strsplit(Target,"")[[1]][1:(length(strsplit(Target,"")[[1]])-3)],collapse=""),"AAAAAA+$")){MatT[j,1]="Long_TrueEnd_OligoA"}
          else if (str_detect(Target, "AA+$") && nchar(Target) >= 2){MatT[j,1]="Long_TrueEnd_OligoA"}
          else if ((grepl("^[AA]+", Target, perl=T) || grepl("[AA]+$", Target, perl=T)) && length(table(unlist(strsplit(Target,"")))) <= 2 && nchar(Target) >= 2){MatT[j,1]="Long_TrueEnd_OligoA"}
          else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && ((!str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) || !str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Long_TrueEnd_Extra"}
        }
        else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Long_TrueEnd_Extra"}
      }
      if (Qcod != Scod && nchar(T[[j]][[2]]) > Len){
        if(grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) <= 1 && Target != "A"){MatT[j,1]="Long_notrueend"}
        else if (!grepl("^[AA]+$", Target, perl=T) && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) != "NaN" && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) == 100){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Long_notrueend_Extra"}
        }
        else if (str_detect(Target, "^A+$") && nchar(Target) >= 1){MatT[j,1]="Long_notrueend_OligoA"}
        else if (grepl("^[A-Z]+", Target, perl=T) && (str_detect(Target, "^AAA+") || str_detect(Target, "AAA+$")) && length(table(unlist(strsplit(Target,"")))) >= 2){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) > 2 && ((str_detect(Target, "^AAAA+") && str_detect(Target, "AAA+$")) || (str_detect(Target, "^AAAA+") || str_detect(Target, "AAA+$")))  && length(names(table(strsplit(Target,"")[[1]]))) > 2){MatT[j,1]="Long_notrueend_ExtraOligoA"}
          else if (grepl("^[A-Z]+", Target, perl=T) && nchar(Target) >=4 && str_detect(paste(strsplit(Target,"")[[1]][1:(length(strsplit(Target,"")[[1]])-3)],collapse=""),"AAAAAA+$")){MatT[j,1]="Long_notrueend_OligoA"}
          else if (str_detect(Target, "AA+$") && nchar(Target) >= 2){MatT[j,1]="Long_notrueend_OligoA"}
          else if ((grepl("^[AA]+", Target, perl=T) || grepl("[AA]+$", Target, perl=T)) && length(table(unlist(strsplit(Target,"")))) <= 2 && nchar(Target) >= 2){MatT[j,1]="Long_notrueend_OligoA"}
          else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && ((!str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) || !str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Long_notrueend_Extra"}
        }
        else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Long_notrueend_Extra"}
      }
      if (Qcod == Scod && nchar(T[[j]][[2]]) < Len){
        if(grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) <= 1 && Target != "A"){MatT[j,1]="Short_TrueEnd"}
        else if (!grepl("^[AA]+$", Target, perl=T) && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) != "NaN" && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) == 100){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Short_TrueEnd_Extra"}
        }
        else if (str_detect(Target, "^A+$") && nchar(Target) >= 1){MatT[j,1]="Short_TrueEnd_OligoA"}
        else if (grepl("^[A-Z]+", Target, perl=T) && (str_detect(Target, "^AAA+") || str_detect(Target, "AAA+$")) && length(table(unlist(strsplit(Target,"")))) >= 2){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) > 2 && ((str_detect(Target, "^AAAA+") && str_detect(Target, "AAA+$")) || (str_detect(Target, "^AAAA+") || str_detect(Target, "AAA+$")))  && length(names(table(strsplit(Target,"")[[1]]))) > 2){MatT[j,1]="Short_TrueEnd_ExtraOligoA"}
          else if (grepl("^[A-Z]+", Target, perl=T) && nchar(Target) >=4 && str_detect(paste(strsplit(Target,"")[[1]][1:(length(strsplit(Target,"")[[1]])-3)],collapse=""),"AAAAAA+$")){MatT[j,1]="Short_TrueEnd_OligoA"}
          else if (str_detect(Target, "AA+$") && nchar(Target) >= 2){MatT[j,1]="Short_TrueEnd_OligoA"}
          else if ((grepl("^[AA]+", Target, perl=T) || grepl("[AA]+$", Target, perl=T)) && length(table(unlist(strsplit(Target,"")))) <= 2 && nchar(Target) >= 2){MatT[j,1]="Short_TrueEnd_OligoA"}
          else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && ((!str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) || !str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Short_TrueEnd_Extra"}
        }
        else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Short_TrueEnd_Extra"}
      }
      if (Qcod != Scod && nchar(T[[j]][[2]]) < Len){
        if(grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) <= 1 && Target != "A"){MatT[j,1]="Short_notrueend"}
        else if (!grepl("^[AA]+$", Target, perl=T) && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) != "NaN" && pid(pairwiseAlignment(as.vector(Target), xSeq, gapOpening=5,gapExtension=5, scoreOnly = FALSE)) == 100){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Short_notrueend_Extra"}
        }
        else if (str_detect(Target, "^A+$") && nchar(Target) >= 1){MatT[j,1]="Short_notrueend_OligoA"}
        else if (grepl("^[A-Z]+", Target, perl=T) && (str_detect(Target, "^AAA+") || str_detect(Target, "AAA+$")) && length(table(unlist(strsplit(Target,"")))) >= 2){
          if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) > 2 && ((str_detect(Target, "^AAAA+") && str_detect(Target, "AAA+$")) || (str_detect(Target, "^AAAA+") || str_detect(Target, "AAA+$")))  && length(names(table(strsplit(Target,"")[[1]]))) > 2){MatT[j,1]="Short_notrueend_ExtraOligoA"}
          else if (grepl("^[A-Z]+", Target, perl=T) && nchar(Target) >=4 && str_detect(paste(strsplit(Target,"")[[1]][1:(length(strsplit(Target,"")[[1]])-3)],collapse=""),"AAAAAA+$")){MatT[j,1]="Short_notrueend_OligoA"}
          else if (str_detect(Target, "AA+$") && nchar(Target) >= 2){MatT[j,1]="Short_notrueend_OligoA"}
          else if ((grepl("^[AA]+", Target, perl=T) || grepl("[AA]+$", Target, perl=T)) && length(table(unlist(strsplit(Target,"")))) <= 2 && nchar(Target) >= 2){MatT[j,1]="Short_notrueend_OligoA"}
          else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && ((!str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) || !str_detect(Target, "^AAAA+") && !str_detect(Target, "AAAA+$")) && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Short_notrueend_Extra"}
        }
        else if (grepl("^[A-Z]+$", Target, perl=T) && nchar(Target) >= 2 && length(names(table(strsplit(Target,"")[[1]]))) >= 1){MatT[j,1]="Short_notrueend_Extra"}
      }
    }
  }
  BltFastaSub[[i]]$ReadGroup=MatT[,1]
}

#Remove the reads with no 3' end flag.
BltFastaSub_v2=list()
for (i in 1:length(BltFastaSub)){
  if (length(which(is.na(BltFastaSub[[i]][,25]))) > 0){
    BltFastaSub_v2[[i]]=BltFastaSub[[i]][-which(is.na(BltFastaSub[[i]][,25])),]
  } else { BltFastaSub_v2[[i]] = BltFastaSub[[i]]}
}
names(BltFastaSub_v2)=names(BltFastaSub)

#Further clean up of the table for polyA+ tail. If the polyA+ is longer that 6 A+ base pair, then considered as ployA+ tail
for (i in 1:length(BltFastaSub_v2)){
  for (j in 1:length(BltFastaSub_v2[[i]][,25])){
    if (BltFastaSub_v2[[i]][,25][j] == "TrueEnd_OligoA" || BltFastaSub_v2[[i]][,25][j] == "Long_TrueEnd_OligoA" || BltFastaSub_v2[[i]][,25][j] == "Short_TrueEnd_OligoA"){
      T=str_extract_all(as.character(as.character(BltFastaSub_v2[[i]][,24][j])),"A-Z][a-z]*|[a-z]+|[A-Z]+")[[1]]
      if (length(T) == 2 && grepl("^[a-z]+$", T[1], perl=T) && nchar(T[2]) < 6){BltFastaSub_v2[[i]][j,25]=gsub("OligoA","ExtraOligoA",BltFastaSub_v2[[i]][,25][j],fix=TRUE)}
      else if (length(T) == 2 && grepl("^[a-z]+$", T[1], perl=T) && !str_detect(T[2], "^A+$")){
        Target=T[2]
        if (length(table(strsplit(Target,"")[[1]])) == 2 && table(strsplit(Target,"")[[1]])[2] >= 2){BltFastaSub_v2[[i]][j,25]=gsub("OligoA","ExtraOligoA",BltFastaSub_v2[[i]][,25][j],fix=TRUE)}
        else if (length(table(strsplit(Target,"")[[1]])) == 3 && sum(table(strsplit(Target,"")[[1]])[2:3]) > 2){BltFastaSub_v2[[i]][j,25]=gsub("OligoA","ExtraOligoA",BltFastaSub_v2[[i]][,25][j],fix=TRUE)}
        else if (length(table(strsplit(Target,"")[[1]])) == 4 && sum(table(strsplit(Target,"")[[1]])[2:4]) > 2){BltFastaSub_v2[[i]][j,25]=gsub("OligoA","ExtraOligoA",BltFastaSub_v2[[i]][,25][j],fix=TRUE)}
      }
      else if (length(T) == 3 && grepl("^[a-z]+$", T[2], perl=T) && nchar(T[3]) < 6){BltFastaSub_v2[[i]][j,25]=gsub("OligoA","ExtraOligoA",BltFastaSub_v2[[i]][,25][j],fix=TRUE)}
      else if (length(T) == 3 && grepl("^[a-z]+$", T[2], perl=T) && !str_detect(T[3], "^A+$")){
        Target=T[3]
        if (length(table(strsplit(Target,"")[[1]])) == 2 && table(strsplit(Target,"")[[1]])[2] >= 2){BltFastaSub_v2[[i]][j,25]=gsub("OligoA","ExtraOligoA",BltFastaSub_v2[[i]][,25][j],fix=TRUE)}
        else if (length(table(strsplit(Target,"")[[1]])) == 3 && sum(table(strsplit(Target,"")[[1]])[2:3]) > 2){BltFastaSub_v2[[i]][j,25]=gsub("OligoA","ExtraOligoA",BltFastaSub_v2[[i]][,25][j],fix=TRUE)}
        else if (length(table(strsplit(Target,"")[[1]])) == 4 && sum(table(strsplit(Target,"")[[1]])[2:4]) > 2){BltFastaSub_v2[[i]][j,25]=gsub("OligoA","ExtraOligoA",BltFastaSub_v2[[i]][,25][j],fix=TRUE)}
      }
    }
  }
}
